import { NgModule } from '@angular/core';
import {
  MatExpansionModule,
  MatSelectModule,
  MatAutocompleteModule,
  MatGridListModule,
  MatDatepickerModule,
  MatRadioModule,
  MatSortModule,
  MatTabsModule,
  MatStepperModule,
  MatPaginatorModule,
  MatTableModule,
  MatDividerModule,
  MatDialogModule,
  MatSnackBarModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatCardModule,
  MatInputModule,
  MatFormFieldModule,
  MatMenuModule,
  MatButtonModule,
  MatListModule,
  MatCheckboxModule,
  MatToolbarModule,
  MatTooltipModule,
  MatIconModule,
  MatChipsModule,
  MatBadgeModule,
  MAT_DATE_FORMATS,
  MatSlideToggleModule,
  MatTreeModule,
} from '@angular/material';
import {MatSidenavModule} from '@angular/material/sidenav';

export const MY_FORMATS = {
  parse: {
    dateInput: 'LL',
  },
  display: {
    dateInput: 'LL',
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
  },
};

@NgModule({
  imports: [
    MatExpansionModule,
    MatSelectModule,
    MatAutocompleteModule,
    MatGridListModule,
    MatDatepickerModule,
    MatRadioModule,
    MatSortModule,
    MatTabsModule,
    MatStepperModule,
    MatPaginatorModule,
    MatTableModule,
    MatDividerModule,
    MatDialogModule,
    MatSnackBarModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatCardModule,
    MatInputModule,
    MatFormFieldModule,
    MatMenuModule,
    MatListModule,
    MatIconModule,
    MatToolbarModule,
    MatTooltipModule,
    MatButtonModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatChipsModule,
    MatBadgeModule,
    MatSlideToggleModule,
    MatTreeModule,
  ],
  exports: [
    MatExpansionModule,
    MatSelectModule,
    MatAutocompleteModule,
    MatGridListModule,
    MatDatepickerModule,
    MatRadioModule,
    MatSortModule,
    MatTabsModule,
    MatStepperModule,
    MatPaginatorModule,
    MatTableModule,
    MatDividerModule,
    MatDialogModule,
    MatSnackBarModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatCardModule,
    MatInputModule,
    MatFormFieldModule,
    MatMenuModule,
    MatListModule,
    MatIconModule,
    MatToolbarModule,
    MatTooltipModule,
    MatButtonModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatChipsModule,
    MatBadgeModule,
    MatSlideToggleModule,
    MatTreeModule
  ],
  providers: [
    {provide: MAT_DATE_FORMATS, useValue: MY_FORMATS},
  ]
})
export class AppMaterialModule { }
